version: '3.8'
services:
  squire:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT:-3333}
        APP_KEY: ${APP_KEY:-}
        LOG_LEVEL: ${LOG_LEVEL:-info}
        SESSION_DRIVER: ${SESSION_DRIVER:-cookie}
    expose:
      - '${PORT:-3333}'
    environment:
      - PORT=${PORT:-3333}
      - NODE_ENV=production
      - APP_KEY=${APP_KEY:-}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - SESSION_DRIVER=${SESSION_DRIVER:-cookie}
    working_dir: /app/build
    command: npm run start
