version: '3.8'
services:
  squire:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT:-3333}
    ports:
      - '${PORT:-3333}:${PORT:-3333}'
    environment:
      - PORT=${PORT:-3333}
      - NODE_ENV=production
    command: npm run start
